### PR TITLE
Refactored, add data-external-replace and support for fragments, map …

### PR DESCRIPTION
**Pull request by ThomasWeinert**
…relative paths in src attributes

I updated the README to document the changes.

### CODE REVIEW

**Comment by janschoepke** [comment]
Hi Thomas, 
wow, thats a massive update, I can't believe my eyes. I already merged the PR, but then I recognized I can't get to work the containing example project anymore. Could you provide a working example with the new version? 
Not to topic: After getting this to work, I will surely update the packages at bower (which you requested in previous pull request) and npm.
Thanks in advance
Jan

**Comment by ThomasWeinert** [comment]
It seems the problem is that the inserted node is the one with 'data-external' and that this breaks the recursion. Please give me a moment. :-)

**Comment by ThomasWeinert** [comment]
You got a new pull request with the fixes

**Comment by janschoepke** [comment]
Thanks. Now it works like a charm.

**Comment by janschoepke** [comment]
New version is out now!

**Pull request merged**
